### ISSUE TITLE
Episodes Randomly playing in background...

### ISSUE THREAD

**Issue by b1n4ryk1lla** [MALSync/MALSync#237]
without any sites open in chrome let the browser sit after some time (10min-1hr) you will hear anime in the background after clicking remove malsync extension from chrome the sound instantly stopped and hasn't returned

repeatedly was going nuts on twitch youtube facebook etc hearing episodes of dr stone and others i have previously watched after some time even killing chrome all together and opening it just leaving it at the blank startup 

**Additional information:**
 - Browser: chrome
 - Type: chrome extension 
 - Url:

**Comment by lolamtisch** [comment]
I have never encountered that problem. 
But i know why it happens. In the current version the update check is broken, resulting that the pages stay open for a much longer time.
Current workaround:
Disable update Check
![image](https://user-images.githubusercontent.com/12599334/68368381-3c519f80-0138-11ea-8fd2-887af39016e3.png)

**Comment by stapuft** [comment]
happens in Firefox as well, thanks for the "fix" but then that means you have to check for new episodes yourself.

**Comment by henrik9999** [comment]
It will be fixed in next Release

**Comment by lolamtisch** [comment]
Should be fixed in version 0.6.8

**Comment by harrynapier** [comment]
I still have this issue after the update. The notifications now come through but I still get music that starts playing in the background until I disable the extension.

**Comment by lolamtisch** [comment]
@harrynapier 
What page are you using. Could you sent an example URL here?

**Comment by harrynapier** [comment]
![Untitled](https://user-images.githubusercontent.com/49285281/69187910-65e4d080-0b13-11ea-8b66-1fa6222308bd.png)

![image](https://user-images.githubusercontent.com/49285281/69189235-e4427200-0b15-11ea-80a6-f1ae6ec91d7f.png)


Not really sure what your looking for? I have included a screen shot of how the music comes up as well as the only error that I can see in the devtools on chrome. 

Ok after a little investigation it seems that the looping music I get is from the otaku steam closing page: https://otakustream.tv/ . I assume the issue is something to do with the music being played automatically when the page is opened. 

I have changed all my anime that were liked to otakusteam to other sites and will let you know if that works.

**Comment by lolamtisch** [comment]
Yeah that should be the fix for that atm. 
In the near future i will implement a url check so that unsupported pages dont get checked. But that will need some restructuring, so nothing that i can just implement.

**Comment by harrynapier** [comment]
Yup that fixed it, Removing the site from the site access permissions might work as well.

**Comment by lolamtisch** [comment]
No it is the opposite. It does not work because it has no access to the page to remove the audio player.
